apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeploy
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginxdeploy
  namespace: default
spec: 
  type: NodePort
  selector:
    app: myapp
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30002
