apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasettest
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest


---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: frontend
spec:
  containers:
  - name: hello1
    image: ubuntu
    command: ['/bin/bash', '-c', 'sleep 3600']